import {
  Activity,
  Rss,
  Bot,
  Clock,
  Search,
  BarChart2,
  CloudSun,
  StickyNote,
  Globe,
  Radio,
  Link,
  CalendarDays,
  Timer,
} from "lucide-react";
import type { WidgetDefinition } from "@/types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    type: "service-status",
    label: "Status des Services",
    description: "Monitore l'état de disponibilité de vos services",
    icon: Activity,
    defaultSize: "medium",
    defaultConfig: { refreshInterval: 30 },
    componentPath: "ServiceStatusWidget",
  },
  {
    type: "rss-feed",
    label: "Flux RSS",
    description: "Affiche les derniers articles de vos flux RSS",
    icon: Rss,
    defaultSize: "medium",
    defaultConfig: { maxItems: 10 },
    componentPath: "RSSFeedWidget",
  },
  {
    type: "llm-chat",
    label: "LLM Chat",
    description: "Interface de chat avec Ollama",
    icon: Bot,
    defaultSize: "large",
    defaultConfig: { model: "" },
    componentPath: "LLMChatWidget",
  },
  {
    type: "clock",
    label: "Horloge",
    description: "Affiche l'heure et la date en temps réel",
    icon: Clock,
    defaultSize: "small",
    defaultConfig: { format24h: true, showSeconds: false, style: "digital" },
    componentPath: "ClockWidget",
  },
  {
    type: "search-bar",
    label: "Barre de Recherche",
    description: "Recherche rapide via votre moteur préféré",
    icon: Search,
    defaultSize: "medium",
    defaultConfig: { engine: "brave" },
    componentPath: "SearchBarWidget",
  },
  {
    type: "grafana-panel",
    label: "Panel Grafana",
    description: "Intègre un panel Grafana en iframe",
    icon: BarChart2,
    defaultSize: "large",
    defaultConfig: {
      grafanaUrl: "",
      dashboardId: "",
      panelId: "",
      orgId: 1,
      refreshInterval: "off",
      theme: "dark",
      title: "",
    },
    componentPath: "GrafanaPanelWidget",
  },
  {
    type: "weather",
    label: "Météo",
    description: "Météo actuelle et prévisions via OpenWeatherMap",
    icon: CloudSun,
    defaultSize: "medium",
    defaultConfig: { city: "Paris", units: "metric" },
    componentPath: "WeatherWidget",
  },
  {
    type: "quick-notes",
    label: "Notes rapides",
    description: "Zone de texte Markdown persistée localement",
    icon: StickyNote,
    defaultSize: "medium",
    defaultConfig: {},
    componentPath: "QuickNotesWidget",
  },
  {
    type: "public-ip",
    label: "IP Publique",
    description: "Affiche votre IP publique et la localisation",
    icon: Globe,
    defaultSize: "small",
    defaultConfig: { referenceIP: "" },
    componentPath: "PublicIPWidget",
  },
  {
    type: "ping-monitor",
    label: "Ping Monitor",
    description: "Surveille la disponibilité de vos hôtes",
    icon: Radio,
    defaultSize: "medium",
    defaultConfig: { refreshInterval: 30 },
    componentPath: "PingMonitorWidget",
  },
  {
    type: "shortcuts",
    label: "Raccourcis",
    description: "Liste de liens rapides avec emoji et nom",
    icon: Link,
    defaultSize: "small",
    defaultConfig: {},
    componentPath: "ShortcutsWidget",
  },
  {
    type: "calendar",
    label: "Calendrier",
    description: "Vue mensuelle avec mise en évidence d'aujourd'hui",
    icon: CalendarDays,
    defaultSize: "small",
    defaultConfig: {},
    componentPath: "CalendarWidget",
  },
  {
    type: "pomodoro",
    label: "Pomodoro",
    description: "Minuteur Pomodoro 25/5 min avec bague de progression",
    icon: Timer,
    defaultSize: "small",
    defaultConfig: {},
    componentPath: "PomodoroWidget",
  },
];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.type === type);
}
