import {
  Activity,
  Rss,
  Bot,
  Clock,
  Search,
  BarChart2,
  CloudSun,
  StickyNote,
  Globe,
  Radio,
  Link,
  CalendarDays,
  Timer,
  Cpu,
  Quote,
  ArrowLeftRight,
  Hourglass,
  CheckSquare,
  Github,
} from "lucide-react";
import type { WidgetDefinition } from "@/types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // ─── Productivité ────────────────────────────────────────────────────────────
  {
    type: "clock",
    label: "Horloge",
    description: "Affiche l'heure et la date en temps réel",
    icon: Clock,
    defaultSize: "small",
    defaultConfig: { format24h: true, showSeconds: false, style: "digital" },
    category: "Productivité",
    componentPath: "ClockWidget",
  },
  {
    type: "search-bar",
    label: "Barre de Recherche",
    description: "Recherche rapide via votre moteur préféré",
    icon: Search,
    defaultSize: "medium",
    defaultConfig: { engine: "brave" },
    category: "Productivité",
    componentPath: "SearchBarWidget",
  },
  {
    type: "quick-notes",
    label: "Notes rapides",
    description: "Zone de texte Markdown persistée localement",
    icon: StickyNote,
    defaultSize: "medium",
    defaultConfig: {},
    category: "Productivité",
    componentPath: "QuickNotesWidget",
  },
  {
    type: "pomodoro",
    label: "Pomodoro",
    description: "Minuteur Pomodoro 25/5 min avec bague de progression",
    icon: Timer,
    defaultSize: "small",
    defaultConfig: {},
    category: "Productivité",
    componentPath: "PomodoroWidget",
  },
  {
    type: "calendar",
    label: "Calendrier",
    description: "Vue mensuelle avec mise en évidence d'aujourd'hui",
    icon: CalendarDays,
    defaultSize: "small",
    defaultConfig: {},
    category: "Productivité",
    componentPath: "CalendarWidget",
  },
  {
    type: "shortcuts",
    label: "Raccourcis",
    description: "Liste de liens rapides avec emoji et nom",
    icon: Link,
    defaultSize: "small",
    defaultConfig: {},
    category: "Productivité",
    componentPath: "ShortcutsWidget",
  },
  {
    type: "tasks",
    label: "Tâches rapides",
    description: "Liste de tâches persistée localement",
    icon: CheckSquare,
    defaultSize: "medium",
    defaultConfig: {},
    category: "Productivité",
    componentPath: "TasksWidget",
  },
  {
    type: "countdown",
    label: "Compte à rebours",
    description: "Décompte vers une date cible configurable",
    icon: Hourglass,
    defaultSize: "small",
    defaultConfig: { title: "Événement", targetDate: "" },
    category: "Productivité",
    componentPath: "CountdownWidget",
  },
  {
    type: "unit-converter",
    label: "Convertisseur",
    description: "Convertit longueur, masse, température et stockage",
    icon: ArrowLeftRight,
    defaultSize: "medium",
    defaultConfig: {},
    category: "Outils",
    componentPath: "UnitConverterWidget",
  },

  // ─── Monitoring ──────────────────────────────────────────────────────────────
  {
    type: "service-status",
    label: "Status des Services",
    description: "Monitore l'état de disponibilité de vos services",
    icon: Activity,
    defaultSize: "medium",
    defaultConfig: { refreshInterval: 30 },
    category: "Monitoring",
    componentPath: "ServiceStatusWidget",
  },
  {
    type: "ping-monitor",
    label: "Ping Monitor",
    description: "Surveille la disponibilité de vos hôtes",
    icon: Radio,
    defaultSize: "medium",
    defaultConfig: { refreshInterval: 30 },
    category: "Monitoring",
    componentPath: "PingMonitorWidget",
  },
  {
    type: "system-stats",
    label: "Stats Système",
    description: "CPU, RAM et uptime du serveur",
    icon: Cpu,
    defaultSize: "medium",
    defaultConfig: { refreshInterval: 10 },
    category: "Monitoring",
    componentPath: "SystemStatsWidget",
  },

  // ─── Informations ────────────────────────────────────────────────────────────
  {
    type: "weather",
    label: "Météo",
    description: "Météo actuelle et prévisions via Open-Meteo",
    icon: CloudSun,
    defaultSize: "medium",
    defaultConfig: { city: "Paris", units: "metric" },
    category: "Informations",
    componentPath: "WeatherWidget",
  },
  {
    type: "public-ip",
    label: "IP Publique",
    description: "Affiche votre IP publique et la localisation",
    icon: Globe,
    defaultSize: "small",
    defaultConfig: { referenceIP: "" },
    category: "Informations",
    componentPath: "PublicIPWidget",
  },
  {
    type: "rss-feed",
    label: "Flux RSS",
    description: "Affiche les derniers articles de vos flux RSS",
    icon: Rss,
    defaultSize: "medium",
    defaultConfig: { maxItems: 10 },
    category: "Informations",
    componentPath: "RSSFeedWidget",
  },
  {
    type: "quote",
    label: "Citation du jour",
    description: "Citation inspirante via quotable.io",
    icon: Quote,
    defaultSize: "medium",
    defaultConfig: { tags: "inspirational" },
    category: "Informations",
    componentPath: "QuoteWidget",
  },

  // ─── Intégrations ────────────────────────────────────────────────────────────
  {
    type: "grafana-panel",
    label: "Panel Grafana",
    description: "Intègre un panel Grafana en iframe",
    icon: BarChart2,
    defaultSize: "large",
    defaultConfig: {
      grafanaUrl: "",
      dashboardId: "",
      panelId: "",
      orgId: 1,
      refreshInterval: "off",
      theme: "dark",
      title: "",
    },
    category: "Intégrations",
    componentPath: "GrafanaPanelWidget",
  },
  {
    type: "llm-chat",
    label: "LLM Chat",
    description: "Interface de chat avec Ollama",
    icon: Bot,
    defaultSize: "large",
    defaultConfig: { model: "" },
    category: "Intégrations",
    componentPath: "LLMChatWidget",
  },
  {
    type: "github-activity",
    label: "Activité GitHub",
    description: "Flux d'activité publique d'un utilisateur GitHub",
    icon: Github,
    defaultSize: "medium",
    defaultConfig: { username: "", maxItems: 8 },
    category: "Intégrations",
    componentPath: "GitHubActivityWidget",
  },
];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.type === type);
}

export const WIDGET_CATEGORIES = [...new Set(WIDGET_REGISTRY.map((w) => w.category))];
